### ISSUE TITLE
Note generated from leaving travis-tool.sh.cmd file at top-level

### ISSUE THREAD

**Issue by StevenMMortimer** [krlmlr/r-appveyor#151]
Whenever Appveyor runs it shows the following error: 

![image](https://user-images.githubusercontent.com/5299737/57699764-7711c980-7626-11e9-835e-b785e33c83c8.png)

Maybe it's because part of the tools are not cleaned up or added to .Rbuildignore, like is being checked here: https://github.com/krlmlr/r-appveyor/blob/e86a7655bf792dd149651dc9208269db32de814e/r-travis/scripts/travis-tool.sh#L57

or here: 

https://github.com/krlmlr/r-appveyor/blob/1d8e8158d65a8f426aaff6c4cc86a854fc92eb2d/scripts/appveyor-tool.ps1#L172

**Comment by krlmlr** [comment]
Thanks, found it in your build: https://ci.appveyor.com/project/StevenMMortimer/salesforcer/build/job/fmf91l0chui80lgf#L255. In this particular case, I think the problem can be resolved by appending an end-of-line to your `.Rbuildignore` .

I seriously wonder if the package's repository is the best place for this file, particularly because we need to jump through hoops to update `.Rbuildignore` . Perhaps we should copy the file to `C:\Windows` or any other path location?

**Comment by krlmlr** [comment]
See the contents of the generated `.Rbuildignore` :

https://ci.appveyor.com/project/StevenMMortimer/salesforcer/build/job/fmf91l0chui80lgf#L70

**Comment by krlmlr** [comment]
Now always adding a newline to `.Rbuildignore`, should work for your repo out of the box now.
