### ISSUE TITLE
travis-tool.sh run_tests 64-bit?

### ISSUE THREAD

**Issue by cdeterman** [krlmlr/r-appveyor#44]
Copied from [r-travis](https://github.com/craigcitro/r-travis/issues/164)

I am trying to use travis-tool.sh on appveyor to install my R package.  However, I would like it to default to the 64 bit version.  Currently [the build](https://ci.appveyor.com/project/cdeterman/gpur) errors out because it is looking for a 64 bit library (that is built during the build) but the default platform is 32-bit despite me explicitly stating the 64-bit platform with my `appveyor.yml`.

>travis-tool.sh run_tests
>...
>...
>using platform: i386-w64-mingw32 (32-bit)

Is there a way to run the travis-tool to use the 64 bit version?

**Comment by krlmlr** [comment]
I guess you can somehow modify the `PATH` environment variable, so that the path to the 64-bit version of R comes before the 32-bit version. However, I'd be very much interested in a proper solution, using an environment variable. See https://github.com/krlmlr/r-appveyor/pull/43/files for an approach to a similar problem (version of gcc toolchain).
