### ISSUE TITLE
Using additional repositories

### ISSUE THREAD

**Issue by iagomosqueira** [krlmlr/r-appveyor#56]
I need to use additional repositories to CRAN for testing some of my packages. I could not find a way to pass them to travis-tool.sh, so for the time being I have had to create my own fork of both r-appveyor and r-travis to add it to the defintion of InstallDeps().

Native r support in travis supports this now, so I see little point in requesting it ([again](https://github.com/craigcitro/r-travis/issues/160)) in there.

Also, I am not sure if this could be achieved in appveyor-tool.ps1, some way of setting options('repos') to include other locations than $CRAN.

Any other ideas about how to allow installation from other repoasitories when resolving package dependencies?

**Comment by krlmlr** [comment]
You could try the "Remotes" or "Additional_Repositories" fields; the deps are installed using devtools::install_deps(), and these fields would be used here.

**Comment by iagomosqueira** [comment]
I had tried with Additional_Repositories but mistakenly had not 
capitalized the second word. Works perfectly, thanks.

**Comment by krlmlr** [comment]
Glad it works for you.

**Comment by maurolepore** [comment]
@iagomosqueira, 

RE _I had tried with Additional_Repositories but mistakenly had not capitalized the second word._

Is it possible that your issue was not capitalization but something else?

The manual [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) refers to `Additional_repositories` -- not `Additional_Repositories`:

> The ‘Depends’, ‘Imports’, ‘Suggests’, ‘Enhances’, ‘LinkingTo’ and ‘Additional_repositories’ fields are discussed in a later subsection.

> The ‘Additional_repositories’ field is a comma-separated list of repository URLs where the packages named in the other fields may be found. It is currently used by R CMD check to check that the packages can be found, at least as source packages (which can be installed on any platform).

(This may not be super important but I think it'd be nice to clarify for those who land in this issue.)
