### ISSUE TITLE
Unavailable packages causing build failure

### ISSUE THREAD

**Issue by cdeterman** [krlmlr/r-appveyor#57]
I have had several builds successfully complete previously but suddenly my build is failing complaining about packages not available.

The build page is [here](https://ci.appveyor.com/project/cdeterman/gpur)

with the relevant lines:

>Packages required but not available: 'Rcpp' 'assertive' 'RcppEigen' 'BH'
Package suggested but not available: 'knitr'

Clearly, these packages should be available as they are all used commonly.

**Comment by krlmlr** [comment]
I'm aware of this, I believe this is because https://cran.r-project.org/bin/windows/contrib/3.4/ is unavailable. Not much I can do about it, but you might ask CRAN.

Try switching to [R-stable or R-patched](https://github.com/krlmlr/r-appveyor/blob/8168fd29410a50807409ca9c1c0643f08a5be009/appveyor.yml#L33-L35) for the time being.

**Comment by krlmlr** [comment]
Actually, it's not CRAN but R-devel who should be consulted for this (R-devel is R 3.3.0, it's dubious why it's accessing the 3.4 path).

**Comment by jimhester** [comment]
@krlmlr R-devel has been bumped to R 3.4 as of [r70342](https://github.com/wch/r-source/commit/50f4f65ccd586e2ed238aaad2d6b54f338062fd0)

**Comment by krlmlr** [comment]
Oh, I see. Then it's dubious why R-devel is 3.4.0... What's 3.3.x then?

**Comment by cdeterman** [comment]
This seems to get part of the way there but now the `devtools` installation appears to be failing as the dependencies `httr`, `jsonlite`, `mime`, `curl`, `openssl` fail to install.  You can see example [here](https://ci.appveyor.com/project/cdeterman/gpur/build/1.0.133).

**Comment by krlmlr** [comment]
@jeroenooms: Is the 3.3.0/3.4.0 confusion due to the new toolchain? I guess it would be safest to default to R-patched for now...

**Comment by jaredhuling** [comment]
This issue is still a problem and the suggested fixes by krlmlr do not work

**Comment by krlmlr** [comment]
@jaredhuling: Could you point me to a failing build?

**Comment by jaredhuling** [comment]
I should have done that initially. Here it is:
https://ci.appveyor.com/project/jaredhuling/oem/build/job/j87ik7jmwh532cw4

**Comment by krlmlr** [comment]
Does it work if you add RcppEigen to the "Imports" of your package?

**Comment by krlmlr** [comment]
Oh, it looks like RcppEigen only has 64-bit libraries. Could you the following setting in appveyor.yml:

```
environment:
  global:
    WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: stable
    R_ARCH: x64
```

See also https://github.com/krlmlr/r-appveyor/blob/7ed23f263873ba51d394b5d2cd5ce451b6c80acf/appveyor.yml#L34 and the surrounding lines.

Could https://github.com/RcppCore/RcppEigen/issues/34 be related?

**Comment by eddelbuettel** [comment]
We do not yet know what https://github.com/RcppCore/RcppEigen/issues/34 actually as it, not unlike Nessy, has only been spotted in one habitat, the Dortmund CRAN builder.  Which has nothing to do with appveyor.  So I'd suggest that it may be best not to refer to it at this point.

**Comment by krlmlr** [comment]
@eddelbuettel: Thanks for chiming in. I only observe that RcppEigen_0.3.2.8.1.zip downloaded from CRAN doesn't have a "libs/i386" directory.

**Comment by jaredhuling** [comment]
@krlmlr  setting to x64 fixed the issue. Thanks

**Comment by wlandau** [comment]
I am currently having a [similar issue](https://ci.appveyor.com/project/wlandau/drake/builds/19453137) where the unavailability of `graph` (through Bioconductor) causes the failure. A couple strange things about that particular failure:

1. `WARNINGS_ARE_ERRORS` was not set, yet the [error message](https://ci.appveyor.com/project/wlandau/drake/builds/19453137#L242) begins with "Error (converted from warning).
2. `graph` was only included in the installation because it is a dependency of `CodeDepends`, which is only a "Suggests" package. `drake` and its tests are ready for `CodeDepends` to be absent, and I strongly prefer to just move on if `graph` cannot be installed.

**Comment by gaborcsardi** [comment]
1. is because of an update to the remotes package, which errors on  warnings  now, unless an env var is set. (see the  remotes  README).

So if you set  the env var, your  build  will continue.  

@krlmlr maybe you  want to set this  by  default?

cc @jimhester

**Comment by wlandau** [comment]
Thanks, @gaborcsardi! A [newer build](https://ci.appveyor.com/project/wlandau/drake/builds/19461190) is continuing as desired. For anyone looking on, I glanced [here](https://github.com/r-lib/remotes#environment-variables) and set `R_REMOTES_NO_ERRORS_FROM_WARNINGS` to `true` [here in `appveyor.yml`](https://github.com/ropensci/drake/blob/f6befe7ccfd947438724c62732680def3c87086a/appveyor.yml#L52).

**Comment by jeroen** [comment]
You can also `setRepositories(ind = 1:4)` before building so that bioc dependencies are automatically available.

**Comment by wlandau** [comment]
Thanks @krlmlr and @jeroen. I may come back to your suggestions depending on how https://github.com/ropensci/drake/issues/41 plays out.

Come to think of it, `drake`'s AppVeyor builds requiring `graph` were actually working until late last night. I see that `graph` version 1.58.2 was released recently, so I guess it may have taken some time for the builds to show up. I like the env var solution because `drake` has 26 "Suggests" packages, and except for 2 or 3 of those, I just skip the affected tests when they are not installed.

**Comment by LiNk-NY** [comment]
Hi all, 
Please look into using `BiocManager::repositories()` and also #125 
Thanks.
