### ISSUE TITLE
Update windows toolchain

### ISSUE THREAD

**Issue by thomasp85** [krlmlr/r-appveyor#94]
When testing on appveyor I'm getting notes related to the registration of native routines (despite these are registered correctly with Rcpp. The check output is below. Following discussion with @jimhester it seems the recent switch in windows toolchain is to blame, resulting in `objdump.exe` not being found on Appveyor build machines...

![screen shot 2017-09-13 at 10 01 04](https://user-images.githubusercontent.com/1775316/30373894-339f4ec0-9883-11e7-938a-fb8ddaf5b148.png)

**Comment by krlmlr** [comment]
Thanks, that's what I'm seeing too. What's the best remedy here?

**Comment by thomasp85** [comment]
AFAIK update/reinstall windows Rtools on R-release?

**Comment by krlmlr** [comment]
But this is done from scratch for every build?

**Comment by jimhester** [comment]
Pretty sure the issue is setting the PATH correctly with the new toolchain,
I can submit a PR on Monday probably.

On Sep 24, 2017 8:45 AM, "Kirill Müller" <notifications@github.com> wrote:

But this is done from scratch for every build?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/krlmlr/r-appveyor/issues/94#issuecomment-331707778>,
or mute
the thread

**Comment by barryrowlingson** [comment]
The people at reticulate seem to have hit this and cracked it:

https://github.com/rstudio/reticulate/blob/master/appveyor.yml

shamelessly copying this into my appveyor.yml fixes objdump.exe not found errors, and bye bye my registration errors too:

```
environment:
 PATH: "%PATH%;C:\\MinGW\\bin;C:\\MinGW\\msys\\1.0;C:\\MinGW\\msys\\1.0\\bin"
```

I don't know which element of PATH objdump.exe is in....

**Comment by jeroen** [comment]
I think it's actually a bug in base-r. It should be using BINPREF to find `objdump`. I'll try to get that fixed.
